### ISSUE TITLE
bam: Invalid pos for unmapped SAM record 

### ISSUE THREAD

**Issue by mnsmar** [biogo/hts#145] opened 2020-01-08 22:58 UTC
Hello,

I am developing a script using `biogo/hts` and I came across this issue. Running `samtools -b` on the output of my script complains `[E::bam_write1] Positional data is too large for BAM format`. I narrowed it down to unmapped reads and specifically in the `Pos` which is set to 4294967296 (highest number represented in uint32).

It seems that this is happening here:
https://github.com/biogo/hts/blob/7c7088b8cd7c18541b06bb87f679604c7039b6d6/bam/reader.go#L439
where `b.bytes(4)` is `[255 255 255 255]` for unmapped reads.

Seems like a bug to me but I'm not sure. Any ideas?

**Comment by kortschak** [comment] 2020-01-09 00:24
@mnsmar Can you try with the change in #146? What seems to be happening, is that 0xffffffff (-1 in `int32` but 4294967296 in `int` when on a 64 bit integer system) causes a problem. I'm not entirely sure how this is happening in your case, since this is during a read and your error is during a write in htslib, but that's what I think is going on. If you post a complete reproducer, I could be more confident.

**Comment by mnsmar** [comment] 2020-01-09 16:49
Thanks for the quick reply. Yes I'm also not sure why this is happening but #146 fixes it. I leave this open until #146 is merged.

**Comment by kortschak** [comment] 2020-01-09 20:09
Reading between the lines, I think that your tool is reading a SAM and emitting a SAM. That would explain why this is happening.

**Comment by kortschak** [comment] 2020-01-09 20:10
Fixed by #146,

**Closed by kortschak** 2020-01-09 20:10 UTC

**Comment by mnsmar** [comment] 2020-01-09 20:24
Yes actually reading BAM, adding an AuxTag to each record and emitting SAM.
