### ISSUE TITLE
Invalid .bam output using hts.bam.Writer

### ISSUE THREAD

**Issue by yipal** [biogo/hts#101] opened 2017-07-27 18:35 UTC
Hi all,
I have been using the biogo library, and it's really great for what I need, but when I produce some output bam files using hts.bam.Wrtier, I encounter some errors.  When I run the output bam file through a checker, I get some errors regarding some INVALID_INDEXING_BIN and INVALID_INDEX_FILE_POINTER errors from picard.

If I then read in the same bam file through biogo's Reader using an index, some of the records do not come through.

I've attached some code that seems to reproduce some of the problems.  What's interesting is that if I change refLen and readRange to be 10x smaller, I no longer see the errors.
[main.go.txt](https://github.com/biogo/hts/files/1180903/main.go.txt)

When I run the code and then check the bam output, these are the errors I get from picard and sambamba (you can ignore the platform errors):

ayip@ayip:~/fun/go/src/main$ go run main.go

ayip@ayip:~/fun/go/src/main$ picard ValidateSamFile I=testoutput.bam MAX_OUTPUT=5
[Thu Jul 27 11:25:03 PDT 2017] picard.sam.ValidateSamFile INPUT=testoutput.bam MAX_OUTPUT=5    MODE=VERBOSE IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Jul 27 11:25:03 PDT 2017] Executing as ayip@ayip on Linux 4.10.0-27-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11; Picard version: 2.10.3-SNAPSHOT
ERROR: Read name name, The platform (PL) attribute (plat) + was not one of the valid values for read group 
ERROR: Record 4194304, Read name r:536870657, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
ERROR: Record 4194305, Read name r:536870913, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
ERROR: Record 4194306, Read name r:536870913, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
ERROR: Record 4194307, Read name r:536871169, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
Maximum output of [5] errors reached.
[Thu Jul 27 11:25:13 PDT 2017] picard.sam.ValidateSamFile done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=959447040
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

ayip@ayip:~/fun/go/src/main$ sambamba_v0.6.6 index -c testoutput.bam 
sambamba-index: Bin in read with name 'r:536870657' is set incorrectly (65535 instead of expected 0)

**Comment by kortschak** [comment] 2017-07-27 21:30
Can you please reduce that reproducer so that there is only a single, simple record (no sequence, no aux tags etc) and only a simple header (no read groups etc). Please post it here in text rather then attaching it.

**Comment by yipal** [comment] 2017-07-27 21:41
Sure, here's a smaller reproduction.  It does produce other errors related to the missing fields though:

package main
import (
    "fmt"
    "github.com/biogo/hts/bam"
    "github.com/biogo/hts/sam"
    "os"
    "strconv"
)

func main() {
    refLen := 2000000000
    readRange := 1000000000

    header, err := sam.NewHeader(nil, nil)
    if err != nil {
        fmt.Printf("problem creating header: %s\n", err)
    }
    ref, err := sam.NewReference("fakeref", "foo", "fakespec", refLen, nil, nil)
    if err != nil {
        fmt.Printf("problem creating reference: %s\n", err)
    }
    err = header.AddReference(ref)
    if err != nil {
        fmt.Printf("problem adding reference: %s\n", err)
    }

    outputStream, err := os.Create("testoutput.bam")
    if err != nil {
        fmt.Printf("problem creating file: %s\n", err)
    }

    writer, err := bam.NewWriter(outputStream, header, 8)
    if err != nil {
        fmt.Printf("problem creating writer: %s\n", err)
    }

    length := 128

    cigar := []sam.CigarOp{sam.NewCigarOp(sam.CigarMatch, length)}

    for i := 1; i <= readRange; i += length * 2 {
        r1 := sam.Record{
            Name:    "r:" + strconv.Itoa(i),
            Ref:     ref,
            Pos:     i,
            MapQ:    byte(length),
            Cigar:   cigar,
            Flags:   sam.Paired | sam.Read1 | sam.MateReverse,
            MateRef: ref,
            MatePos: i + length,
            TempLen: length,
        }
        writer.Write(&r1)
    }
    writer.Close()
}

Thanks again for your help!
- Alex

**Comment by kortschak** [comment] 2017-07-27 21:45
Please, just output a *single record* that fails your test with sambamba.

**Comment by kortschak** [comment] 2017-07-27 21:47
You should close your files.

**Comment by yipal** [comment] 2017-07-27 21:59
I added a line to call outputStream.Close() at the end of main() with no change in the errors.

I have not been able to reproduce the INVALID_INDEXING_BIN problem with a smaller number of reads.  If I reduce the readRange by a factor of 2, then picard reports zero INVALID_INDEXING_BIN errors.  I suspect that the problem may be related to the number of reads.

**Comment by kortschak** [comment] 2017-07-27 22:25
You don't need to write all the records in that range, only one that fails - identified by the record name; a bam record stream is stateless so there should be no dependence on the number of reads. From the description of the issue, this is an error in calculating the bin number in my code - this is absolutely stateless.

**Comment by kortschak** [comment] 2017-07-27 22:32
Does this produce a failing file for you on stout (note that you were conflating read length and template length - so I have removed template length from the record).

```
package main

import (
        "fmt"
        "os"
        "strconv"

        "github.com/biogo/hts/bam"
        "github.com/biogo/hts/sam"
)

func main() {
        const (
                refLen = 2000000000
                pos    = 536870913
                length = 128
        )

        header, err := sam.NewHeader(nil, nil)
        if err != nil {
                fmt.Printf("problem creating header: %s\n", err)
        }
        ref, err := sam.NewReference("fakeref", "foo", "fakespec", refLen, nil, nil)
        if err != nil {
                fmt.Printf("problem creating reference: %s\n", err)
        }
        err = header.AddReference(ref)
        if err != nil {
                fmt.Printf("problem adding reference: %s\n", err)
        }

        w, err := bam.NewWriter(os.Stderr, header, 8)
        if err != nil {
                fmt.Printf("problem creating writer: %s\n", err)
        }

        w.Write(&sam.Record{
                Name:  "r:" + strconv.Itoa(pos),
                Ref:   ref,
                Pos:   pos,
                Cigar: []sam.CigarOp{sam.NewCigarOp(sam.CigarMatch, length)},
        })
        w.Close()       
}       
```

**Comment by yipal** [comment] 2017-07-27 22:36
Yes, with your code, picard reports these errors:
ERROR:EMPTY_READ	1
ERROR:INVALID_INDEXING_BIN	1
ERROR:MISSING_READ_GROUP	1

More specifically:
ERROR: Read groups is empty
ERROR: Record 1, Read name r:536870913, Zero-length read without FZ, CS or CQ tag
ERROR: Record 1, Read name r:536870913, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned

**Comment by kortschak** [comment] 2017-07-27 22:41
OK. We do need some of the fluff above. I'm not interested in picard output though, it's largely useless here. Unfortunately I'm unable to get sambamba to build.

**Comment by yipal** [comment] 2017-07-27 22:52
If I limit the records using the if condition below to just r:536870913, then sambamba does not complain.
If I remove the if condition, then sambamba does report this:

sambamba-index: Bin in read with name 'r:536870913' is set incorrectly (65535 instead of expected 37449)


```package main

import (
    "fmt"
    "github.com/biogo/hts/bam"
    "github.com/biogo/hts/sam"
    "os"
    "strconv"
)

func main() {
    refLen := 2000000000
    readRange := 1000000000

    header, err := sam.NewHeader(nil, nil)
    if err != nil {
        fmt.Printf("problem creating header: %s\n", err)
    }
    ref, err := sam.NewReference("fakeref", "foo", "fakespec", refLen, nil, nil)
    if err != nil {
	fmt.Printf("problem creating reference: %s\n", err)
    }
    err = header.AddReference(ref)
    if err != nil {
	fmt.Printf("problem adding reference: %s\n", err)
    }

    outputStream, err := os.Create("testoutput.bam")
    if err != nil {
	fmt.Printf("problem creating file: %s\n", err)
    }

    writer, err := bam.NewWriter(outputStream, header, 1)
    if err != nil {
	fmt.Printf("problem creating writer: %s\n", err)
    }

    length := 128

    cigar := []sam.CigarOp{sam.NewCigarOp(sam.CigarMatch, length)}

    for i := 1; i <= readRange; i += length * 2 {
	if i == 536870913 {
            r1 := sam.Record{
                Name:    "r:" + strconv.Itoa(i),
                Ref:     ref,
                Pos:     i,
                MapQ:    byte(length),
                Cigar:   cigar,
                Flags:   sam.Paired | sam.Read1 | sam.MateReverse,
                MateRef: ref,
                MatePos: i + length,
                TempLen: length,
            }
            writer.Write(&r1)
        }
    }
    writer.Close()
    outputStream.Close()
}
```

**Comment by kortschak** [comment] 2017-07-27 22:58
OK, the failing record is at 536,870,913, but from the specification "This implies that this index format does not support reference chromosome sequences longer than 2^29 − 1." (because no one will ever need more than 640kb).

The Bin method checks validity of the record location and correctly fails in this case, returning a correctly invalid (-1) bin.

Why do you need to use such a large reference? Are you working on plants?

I'm curious as to how/why sambamba and picard return apparently valid bin numbers there (if I remove the position validity check, I get the value sambamba reports above: 37449).

/cc @lomereiter

**Comment by yipal** [comment] 2017-07-27 23:14
Maybe this test program is not triggering the same error that my application code is triggering.  In my application, one of the reads that trigger an error in sambamba is at position 3596444.

Sambamba reports:
sambamba-index: Bin in read with name 'SN1279:510:C8EL3ANXX:4:1315:17239:8943' is set incorrectly (4680 instead of expected 4900)

**Comment by yipal** [comment] 2017-07-27 23:28
Unfortunately, I can't provide the actual file I have with the errors, but I can provide another pattern I noticed.

In the read names that picard reports an error for, there is a pair of reads, and the first read that appears in the file is unmapped, and shares the same position as its mate which is mapped, and appears later in the file.

**Comment by kortschak** [comment] 2017-07-27 23:30
Please give me the full SAM-encoded read/pair (doesn't need to be the whole file - actually would prefer not) and the relevant SAM header. An English description of a pattern is almost entirely non-debuggable. So in the absence of some hard data I'm going to have to close this.

Note that in your code above https://github.com/biogo/hts/issues/101#issuecomment-318508731, there is absolutely no need for the for loop. As sufficiently intelligent compiler would optimize

```
    for i := 1; i <= readRange; i += length * 2 {
	if i == 536870913 {
            r1 := sam.Record{
                Name:    "r:" + strconv.Itoa(i),
                Ref:     ref,
                Pos:     i,
                MapQ:    byte(length),
                Cigar:   cigar,
                Flags:   sam.Paired | sam.Read1 | sam.MateReverse,
                MateRef: ref,
                MatePos: i + length,
                TempLen: length,
            }
            writer.Write(&r1)
        }
    }
```
to
```
    i := 536870913
    r1 := sam.Record{
        Name:    "r:" + strconv.Itoa(i),
        Ref:     ref,
        Pos:     i,
        MapQ:    byte(length),
        Cigar:   cigar,
        Flags:   sam.Paired | sam.Read1 | sam.MateReverse,
        MateRef: ref,
        MatePos: i + length,
        TempLen: length,
    }
    writer.Write(&r1)
```

**Comment by yipal** [comment] 2017-07-27 23:49
I think I know what's going on here.  In my file, there are unmapped reads that appear in between mapped reads, as opposed to putting all the unmapped reads at the end of the bam file.  

When record.Bin() computes the bin, it checks if the read is unmapped here:
https://github.com/biogo/hts/blob/master/sam/record.go#L132

and returns 4680.  Perhaps the other tools allow the unmapped reads to exist in between mapped reads.

If I remove the lines that check for unmapped and returns 4680, I no longer see any Bin errors from picard or sambamba.

**Comment by kortschak** [comment] 2017-07-28 00:10
You must sort your reads if you want to use an index.

**Comment by yipal** [comment] 2017-07-28 00:24
According to the SAM/BAM spec, section 2 bullet 4.1, regarding unmapped reads, says that:

"For a unmapped paired-end or mate-pair read whose mate is mapped, the unmapped read should have RNAME and POS identical to it's mate."

This is the case in the file I'm reading and writing.  I have a read pair where one read is mapped, and the other read is unmapped.  So both reads in the pair have the same position.  So the file is correctly sorted by position, and the unmapped read has the same position as its mapped mate.  I think the check at line record.go:132 is probably incorrect because an unmapped read might have a legitimate position, and therefore the unmapped read should get a legitimate bin in that case.

What do you think?

**Comment by kortschak** [comment] 2017-07-28 00:27
I'll look into that later today.

**Comment by kortschak** [comment] 2017-07-28 01:47
Please try with your code and the following change in hts.

```diff
diff --git a/sam/record.go b/sam/record.go
index 30d1959..f9f8f4d 100644
--- a/sam/record.go
+++ b/sam/record.go
@@ -128,7 +128,7 @@ func (r *Record) Start() int {
 
 // Bin returns the BAM index bin of the record.
 func (r *Record) Bin() int {
-       if r.Flags&Unmapped != 0 {
+       if r.Flags&(Unmapped|MateUnmapped) == Unmapped|MateUnmapped {
                return 4680 // reg2bin(-1, 0)
        }
        end := r.End()
```

This change requires that you conform to the specification as stated above (it does not check that you do and will return an incorrect bin value if you don't. There is no way for me to retain the current API and keep safety here.

**Comment by yipal** [comment] 2017-07-28 18:28
Hi Dan, this change does address the problem I had.  Thanks for all your help!

**Closed** 2017-07-30 06:53 UTC
